### ISSUE TITLE
Unhandled exception: type 'SocketException' is not a subtype of type 'AsyncError'

### ISSUE THREAD

**Issue by Pacane** [dart-db/sqljocky5#22]
When running an app using SQLJocky5 I get this error eventually (Maybe the server went down or something)

```dart
Unhandled exception:
type 'SocketException' is not a subtype of type 'AsyncError'
#0      BufferedSocket._onSocketError (package:sqljocky5/comm/buffered_socket.dart:48:15)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:370:18)
#4      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7)
#5      _SyncStreamController._sendError (dart:async/stream_controller.dart:767:19)
#6      _StreamController._addError (dart:async/stream_controller.dart:647:7)
#7      _StreamController.addError (dart:async/stream_controller.dart:599:5)
#8      new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1296:23)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1353:26)
#11     _NativeSocket.reportError (dart:io/runtime/binsocket_patch.dart:1067:32)
#12     _NativeSocket.multiplex (dart:io/runtime/binsocket_patch.dart:905:13)
#13     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Caused by 
```dart
typedef ErrorHandler(AsyncError err);
```

being used here 

```dart
  BufferedSocket._(this._socket, this.onDataReady, this.onDone, this.onError,
      this.onClosed) {
    _subscription = _socket.listen(_onData,
        onError: _onSocketError, onDone: _onSocketDone, cancelOnError: true);
  }

  _onSocketError(error) {
    if (onError != null) {
      onError(error);
    }
  }
```

**Comment by Pacane** [comment]
@tejainece seems like this is fixed in the master branch but not released to pub. Could you make a new release? Thanks!

**Comment by tejainece** [comment]
Hi,

Sorry for late reply. I will publish the latest code soon. I will also try to reproduce this error.

**Comment by tejainece** [comment]
@Pacane I have released the latest code on github as `2.2.1`. I, however, have not tested if it fixes the issue. I will test it tomorrow. Please let me know, if this has already fixed the issue.

Thanks!

**Comment by tejainece** [comment]
@Pacane Did it fix the issue?

**Comment by Pacane** [comment]
I'm currently running this in a testing environment, I'll give it about 24 hours to see if the issue happens.

I'll reopen an issue if it's happening again.

Thanks

**Comment by tejainece** [comment]
Thanks!
